-- AlterTable
ALTER TABLE "Hero" ADD COLUMN     "baseArmor" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "baseHealth" INTEGER NOT NULL DEFAULT 250,
ADD COLUMN     "baseShields" INTEGER NOT NULL DEFAULT 0;
