import type { Power, Prisma } from "$src/generated/prisma";

export const ItemRarity = {
  Common: "Common",
  Rare: "Rare",
  Epic: "Epic",
} as const;
export type ItemRarity = (typeof ItemRarity)[keyof typeof ItemRarity];

export const ItemCategory = {
  Weapon: "Weapon",
  Ability: "Ability",
  Survival: "Survival",
} as const;
export type ItemCategory = (typeof ItemCategory)[keyof typeof ItemCategory];

export const FullStatModInclude = { stat: true };
export const FullItemInclude = {
  statMods: {
    include: {
      stat: {
        include: {
          statMods: {
            include: FullStatModInclude,
            orderBy: {
              orderIndex: "asc",
            },
          },
        },
      },
    },
    orderBy: {
      orderIndex: "asc",
    },
  },
} as const satisfies Prisma.ItemInclude;
export type FullItem = Prisma.ItemGetPayload<{ include: typeof FullItemInclude }>;

export type FullStatMod = Prisma.StatModGetPayload<{ include: typeof FullStatModInclude }>;

export const FullRoundInfoSectionInclude = {
  purchasedItems: {
    include: FullItemInclude,
  },
  soldItems: {
    include: FullItemInclude,
  },
  power: true,
} as const satisfies Prisma.RoundInfoSectionInclude;

export const FullRoundInfoInclude = {
  sections: {
    include: FullRoundInfoSectionInclude,
    orderBy: {
      orderIndex: "asc",
    },
  },
} as const satisfies Prisma.RoundInfoInclude;

export const FullStadiumBuildInclude = {
  author: true,
  hero: true,
  roundInfos: {
    include: FullRoundInfoInclude,
    orderBy: {
      orderIndex: "asc",
    },
  },
} as const satisfies Prisma.StadiumBuildInclude;

export type FullStadiumBuild = Prisma.StadiumBuildGetPayload<{
  include: typeof FullStadiumBuildInclude;
}>;

export type AutoGeneratedFields = "id" | "createdAt" | "updatedAt";

export type FlatFullRoundInfoSection = Omit<
  Prisma.RoundInfoSectionUncheckedCreateWithoutParentRoundInfoInput,
  AutoGeneratedFields | "purchasedItems" | "soldItems" | "powerId"
> & {
  power: Power | null;
  purchasedItems: FullItem[];
  soldItems: FullItem[];
};

export type FlatFullRoundInfo = Omit<
  Prisma.RoundInfoUncheckedCreateWithoutParentBuildInput,
  AutoGeneratedFields
> & {
  sections: FlatFullRoundInfoSection[];
};

export type FlatFullStadiumBuild = Omit<
  Prisma.StadiumBuildUncheckedCreateInput,
  AutoGeneratedFields | "authorId" | "roundInfos"
> & {
  roundInfos: FlatFullRoundInfo[];
};

export type BuildData = FullStadiumBuild | FlatFullStadiumBuild;
